CREATE DATABASE advertisement;

CREATE USER advertisement_user WITH PASSWORD '46Gx3X9nT1tABLf2Mu';

ALTER DATABASE advertisement OWNER TO advertisement_user;

CREATE SCHEMA advertisement;

ALTER SCHEMA advertisement OWNER TO advertisement_user;

CREATE TABLE advertisement.users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone_number VARCHAR(32) NOT NULL,
    rating INTEGER DEFAULT 0,
    email VARCHAR(255) UNIQUE NOT NULL,
    boosted BOOLEAN DEFAULT FALSE,
    role VARCHAR(50) NOT NULL
);

CREATE TABLE advertisement.advertisements (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL,
    price INTEGER DEFAULT 0,
    headline VARCHAR(50) NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(50) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES advertisement.users(id)
);

CREATE TABLE advertisement.comments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    advertisement_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    text TEXT NOT NULL,
    created_at TIMESTAMP default CURRENT_TIMESTAMP,
    FOREIGN KEY (advertisement_id) REFERENCES advertisement.advertisements(id),
    FOREIGN KEY (user_id) REFERENCES advertisement.users(id)
);

CREATE TABLE advertisement.messages (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    advertisement_id INTEGER NOT NULL,
    sender_id INTEGER NOT NULL,
    recipient_id INTEGER NOT NULL,
    text TEXT NOT NULL,
    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    read BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (advertisement_id) REFERENCES advertisement.advertisements (id),
    FOREIGN KEY (sender_id) REFERENCES advertisement.users (id),
    FOREIGN KEY (recipient_id) REFERENCES advertisement.users (id)
);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA advertisement TO advertisement_user;
