--liquibase formatted sql

--changeset 003-create-advertisements-table:dmitry
CREATE TABLE IF NOT EXISTS advertisement.advertisements (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL,
    price INTEGER DEFAULT 0,
    headline VARCHAR(50) NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(50) DEFAULT 'REVIEW',
    FOREIGN KEY (user_id) REFERENCES advertisement.users(id)
);

-- rollback DROP TABLE IF EXISTS advertisement.advertisements;
