--liquibase formatted sql

--changeset 002-create-users-table:dmitry
CREATE TABLE IF NOT EXISTS advertisement.users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone_number VARCHAR(32) NOT NULL,
    rating INTEGER DEFAULT 0,
    email VARCHAR(255) UNIQUE NOT NULL,
    boosted BOOLEAN DEFAULT FALSE,
    role VARCHAR(50) NOT NULL
);

-- rollback DROP TABLE IF EXISTS advertisement.users;
