--liquibase formatted sql

--changeset 004-create-comments-table:dmitry
CREATE TABLE IF NOT EXISTS advertisement.comments (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    advertisement_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    text TEXT NOT NULL,
    created_at TIMESTAMP default CURRENT_TIMESTAMP,
    FOREIGN KEY (advertisement_id) REFERENCES advertisement.advertisements(id),
    FOREIGN KEY (user_id) REFERENCES advertisement.users(id)
);

-- rollback DROP TABLE IF EXISTS advertisement.comments;
