--liquibase formatted sql

--changeset 005-create-messages-table:dmitry
CREATE TABLE IF NOT EXISTS advertisement.messages (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    advertisement_id INTEGER NOT NULL,
    sender_id INTEGER NOT NULL,
    recipient_id INTEGER NOT NULL,
    text TEXT NOT NULL,
    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    read BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (advertisement_id) REFERENCES advertisement.advertisements (id),
    FOREIGN KEY (sender_id) REFERENCES advertisement.users (id),
    FOREIGN KEY (recipient_id) REFERENCES advertisement.users (id)
);

-- rollback DROP TABLE IF EXISTS advertisement.messages;
