--liquibase formatted sql

--changeset 009-create-ratings-table:dmitry
CREATE TABLE advertisement.ratings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sender_id BIGINT NOT NULL,
    recipient_id BIGINT NOT NULL,
    evaluation INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (sender_id) REFERENCES advertisement.users (id),
    FOREIGN KEY (recipient_id) REFERENCES advertisement.users (id)
);

-- rollback DROP TABLE advertisement.ratings;
